name: gracewireapp
favicon: null
layout_spectrum: 0.817736966535449
typography_spectrum: 0.8143884025048465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b7673'
    - '#fefefe'
    - '#342f2c'
    - '#565251'
    - '#e2d3ce'
  brandStrength: 0.9375
  lightness: 0.4371538411360234
  saturation: 0.9181734507437795
  rhythmicContrast: 0.6733279088512063
purpose: []
