typography_spectrum: 0.8143884025048465
color:
  brandColors:
    - '#ffffff'
    - '#978c92'
    - '#563a2f'
    - '#231717'
    - '#c3b9b1'
  brandStrength: 0.9375
  lightness: 0.4371538411360234
  saturation: 0.9181734507437795
  rhythmicContrast: 0.6733279088512063
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: gracewireapp
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: sssss
purpose: []
